### ISSUE TITLE
请教您配置文件需要怎么修改？

### ISSUE THREAD

**Issue by hu-qi** [xinwuyun/fg#3]
前置步骤通过
```
s init start-fg-http-python3.6 
```
初始化了一个 python 3 环境的云函数,
单部署的时候报错，按照报错信息应该是我这边触发器的配置不对，想请教您，
s.yaml  配置文件还需修改哪些地方？

![image](https://user-images.githubusercontent.com/17986122/171134579-c5840826-cec3-4a33-823d-b67ccb8ada35.png)

目前看到云函数已经上传上去了：
![image](https://user-images.githubusercontent.com/17986122/171134795-c27ef115-3afa-4cf7-888c-15a1224b0d94.png)

已按照如下文档修改部分字段：[https://support.huaweicloud.com/usermanual-functiongraph/functiongraph_01_1813.html](https://support.huaweicloud.com/usermanual-functiongraph/functiongraph_01_1813.html)

**Comment by wang-zerui** [comment]
触发器创建目前还有点问题，有一些参数这个组件还没做自动获取。但是函数可以正常创建，可以先使用 `s deploy function`部署函数。触发器麻烦先用web端控制台创建吧
